k2 <- max_magnitude()
k5 <- max_magnitude()
k8 <- max_magnitude()
k11 <- max_magnitude()
k14 <- max_magnitude()
k17 <- max_magnitude()
k20 <- max_magnitude()
k23 <- max_magnitude()
k26 <- max_magnitude()

par(mfrow = c(3,1))
max_magni <- k2
plot(max_magni$Magnitude, type = 'l', col = 1, lwd = 2, ann = F)
axis(2, at = pretty(c(1.1*min(max_magni$Magnitude),1.1*max(max_magni$Magnitude))), col = 1)
par(new = T)
plot(max_magni$Frequency, type = 'l', ylim = c(0,1.05*max(max_magni$Frequency)), col = 4, axes = F, lwd = 2, ann = F)
axis(4, pretty(c(0,1.05*max(max_magni$Frequency))), col = 4)
par(new = T)
plot(max_magni$Avg_Temp, type = 'l', ylim = c(0,1.1*max(max_magni$Avg_Temp)), col = 2, axes = F, lwd = 3, ann = F)
axis(side = 2, mgp = c(4,1,2), col = 2, las = 1)
# legend('bottomleft', legend = c('Magnitude', 'Frequency', 'Average Temp'), col = c('black', 'blue', 'red'), cex = 0.50, lwd = c(2,2,3))

plot(k2$Magnitude, type = 'l', col = 1)
par(new = T)
plot(k5$Magnitude, type = 'l', col = 4)
par(new = T)
plot(k8$Magnitude, type = 'l', col = 2)

t2 <- data.frame(tabulate(k2$ro_n))
t2$index <- row.names(t2)
t5 <- data.frame(tabulate(k5$ro_n))
t8 <- data.frame(tabulate(k8$ro_n))
v <- max(max(t2$Freq), max(t5$Freq), max(t8$Freq))
w <- max(as.numeric(t2$Var1), as.numeric(t5$Var1), as.numeric(t8$Var1))
par(mfrow = c(3,1))
plot(t2$Freq, type = 'l')
text(c(which.max(t2$Freq),0),c(max(t2$Freq), max(t2$Freq)), labels = c((which(t2$Freq == max(t2$Freq))), max(t2$Freq)))

plot(t5$Freq, type = 'l')
text(c(which.max(t5$Freq),-2),c(max(t5$Freq), max(t5$Freq)), labels = c((which(t5$Freq == max(t5$Freq))), max(t5$Freq)))

plot(t8$Freq, type = 'l', col = 2, ann = F, ylim  = c(0, 1.1*v), xlim = c(0,1.1*w))
text(c(which.max(t8$Freq),-2),c(max(t8$Freq), max(t8$Freq)), labels = c((which(t8$Freq == max(t8$Freq))), max(t8$Freq)))
