---
title: "Magnitude profile study"
author: "Preeti Narayanan"
date: "January 28, 2016"
output: html_document
---

Functions to be used below: 
First convert LVM to CSV and store in the current directory
```{r}
options(warn = -1)
file_import <- function(mypattern) {
  #Creates a list of all the LVM files
  list.filename <- list.files(pattern = mypattern)
  
  #Create an empty list to store the files
  list.data <- list()
  
  #Create a loop to store the files into list.data
  for(i in 1:length(list.filename)){
    list.data[[i]] <- read.delim(list.filename[i],header = FALSE)
  }
  
  maindr <- getwd()
  subdr <- tail(strsplit(maindr, split = '/', fixed = TRUE)[[1]],1)
  
  if (dir.exists(file.path(maindr,subdr)) == FALSE){
    dir.create(file.path(maindr,subdr))
    setwd(file.path(maindr,subdr))
  }
  
  for (j in 4:length(list.filename)){
    y <- data.frame(list.data[j])
    y <- subset(y, select = c(1:5))
    colnames(y) <- c('Frequency', 'Magnitude', 'Phase', 'Inlet Temp', 'Outlet Temp')
    LVM_name <- list.filename[j]
    CSV_name <- unlist(strsplit(LVM_name, split = '.', fixed = TRUE))[1]
    write.csv(y, file = paste0(CSV_name,'.csv'), row.names = FALSE)
  }
  
}

```
Plot  Temperature and Magnitude against Frequency

```{r}
Magnitude_profile_plot <- function(){
  list.filename <- list.files()
  n = length(list.filename)
  
  df_list <- data.frame(matrix(ncol = 7, nrow = 0))
  for (i in 1:n) {
    temp_file <- read.csv(file = list.filename[i])
    temp_file$Avg_Temp <- rowMeans(temp_file[, c(4,5)]) 
    temp_file <- subset(temp_file, select = c(1:3,6))
    df_list[i,] <- c(min(temp_file$Frequency), max(temp_file$Frequency), min(temp_file$Magnitude), max(temp_file$Magnitude),min(temp_file$Phase), max(temp_file$Phase), temp_file$Avg_Temp)
  }
  
  par(mfrow = c(1,3))
  plot(df_list$X3, type = 'l', ylab = 'Minimum Magnitude', col = 23)
  plot(df_list$X4, type = 'l', ylab = 'Maximum Magnitude', col = 24)
  plot(df_list$X4, type = 'l', ylab = NULL, col = 24)
  par(new=T)
  plot(df_list$X7, type= 'l', col = 66)
  par(new = F)
}

```


```{r}
profile_summary <- function(){
  list.filename <- list.files()
  n = length(list.filename)
  
  df_list <- data.frame(matrix(ncol = 7, nrow = 0))
  for (i in 1:n) {
    temp_file <- read.csv(file = list.filename[i])
    temp_file$Avg_Temp <- rowMeans(temp_file[, c(4,5)]) 
    temp_file <- subset(temp_file, select = c(1:3,6))
    df_list[i,] <- c(min(temp_file$Frequency), max(temp_file$Frequency), min(temp_file$Magnitude), max(temp_file$Magnitude),min(temp_file$Phase), max(temp_file$Phase), temp_file$Avg_Temp)
  }
  
  colnames(df_list) <- c('Min Frequency', 'Max Frequency', ' Min Magnitude', 'Max Magnitude', 'Min Phase', 'Max Phase', ' Avg Temp')
  summary(df_list)
  
  }
```

Extract information on soot load using the frequency range

```{r}
extract_freq <- function(){
  #Set working directory
  list.filename <- list.files()
  n = length(list.filename)
  
  df_list <- data.frame(matrix(ncol = 7, nrow = 0))
  for (i in 1:n) {
    temp_file <- read.csv(file = list.filename[i])
    temp_file$Avg_Temp <- rowMeans(temp_file[, c(4,5)]) 
    temp_file <- subset(temp_file, select = c(1:3,6))
    df_list <- rbind(df_list,temp_file)
  }
  
  df_tab <- data.frame(matrix(nrow= 0, ncol = 8))
  freq_range <- unique(df_list$Frequency)
  max_mag <- data.frame(matrix(ncol = 4, nrow = 0))
  min_mag <- data.frame(matrix(ncol = 3, nrow = 0))
  for (j in 1:length(freq_range)){
    a <- df_list[df_list$Frequency == freq_range[j],]
    a <- a[order(a$Magnitude),]
    mag_1 <- a[1,]
    mag_2 <- a[length(a),-1]
    max_mag <- rbind(max_mag,mag_1)
    min_mag <- rbind(min_mag,mag_2)
  }
  
  df_tab <- cbind(max_mag, min_mag)
  colnames(df_tab) <- c('Frequency' , 'Max Magnitude','Max_Phase', 'Max_Temp', 'Min Magnitude', 'Min_Phase', 'Min_Temp')
  rownames(df_tab) <- NULL
  return(df_tab)
}

```

```{r}
setwd("C:/Users/Preeti/Desktop/CTS/MTU Data/2015-09-11_FP037_K2/2015-09-11_FP037_K2")
profile_summary()
Magnitude_profile_plot()
tab_2 <- extract_freq()
```

```{r}
setwd("C:/Users/Preeti/Desktop/CTS/MTU Data/2015-09-14_FP037_K5/2015-09-14_FP037_K5")
b <- profile_summary()
Magnitude_profile_plot()
tab_5 <- extract_freq()
```

```{r}
setwd("C:/Users/Preeti/Desktop/CTS/MTU Data/2015-09-14_FP037_K8/2015-09-14_FP037_K8")
c <- profile_summary()
Magnitude_profile_plot()
tab_8 <- extract_freq()
options(warn = 0)
```
